import dotenv from "dotenv";
dotenv.config();

const PRODUCTION_LEVEL = process.env.PRODUCTION_LEVEL;
const MONGODB_URI = process.env.MONGODB_URI;
const PRODUCTION_PORT = process.env.PRODUCTION_PORT;
const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PORT = process.env.REDIS_PORT;
const PRODUCTION_SECRET_KEY = process.env.PRODUCTION_SECRET_KEY;
const PRODUCTION_REFRESH_SECRET_KEY = process.env.PRODUCTION_REFRESH_SECRET_KEY;

export {
  PRODUCTION_LEVEL,
  PRODUCTION_REFRESH_SECRET_KEY,
  MONGODB_URI,
  PRODUCTION_PORT,
  REDIS_HOST,
  REDIS_PORT,
  PRODUCTION_SECRET_KEY,
};
